version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: rastreamento  
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql 

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: rastreamento
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:  
