name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Etapa 1: Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Etapa 2: Login no Docker Registry (Docker Hub ou ECR)
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Etapa 3: Construir e enviar as imagens Docker
    - name: Build and push Docker image
      run: |
        docker build -t my-app:latest .
        docker tag my-app:latest ghostpointer/my-app:latest
        docker push ghostpointer/my-app:latest

